"""create table master_data

Revision ID: 0398ad4f485f
Revises: d9606d479627
Create Date: 2021-12-07 15:43:22.783586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0398ad4f485f'
down_revision = 'd9606d479627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('opd_id', sa.Integer(), nullable=True),
    sa.Column('satuan', sa.String(length=32), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opd_id'], ['opd.id'], name=op.f('fk_master_data_opd_id_opd')),
    sa.ForeignKeyConstraint(['parent_id'], ['master_data.id'], name=op.f('fk_master_data_parent_id_master_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_data'))
    )
    op.create_index(op.f('ix_master_data_id'), 'master_data', ['id'], unique=False)
    op.create_index(op.f('ix_master_data_parent_id'), 'master_data', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_data_parent_id'), table_name='master_data')
    op.drop_index(op.f('ix_master_data_id'), table_name='master_data')
    op.drop_table('master_data')
    # ### end Alembic commands ###
