"""alter table input data

Revision ID: 11057ca26636
Revises: 2af54026f797
Create Date: 2021-12-30 08:35:51.220384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11057ca26636'
down_revision = '2af54026f797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_data', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('input_data', 'is_active')
    # ### end Alembic commands ###
