"""alter table master_data

Revision ID: 288c067a1155
Revises: 57a1014f1d48
Create Date: 2021-12-30 11:22:00.588415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288c067a1155'
down_revision = '57a1014f1d48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_data', sa.Column('validation_flow_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_master_data_validation_flow_id_validation_flow'), 'master_data', 'validation_flow', ['validation_flow_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_master_data_validation_flow_id_validation_flow'), 'master_data', type_='foreignkey')
    op.drop_column('master_data', 'validation_flow_id')
    # ### end Alembic commands ###
