"""alter table satuan

Revision ID: 2ea26f2e4824
Revises: 740e06bcdeaa
Create Date: 2021-12-16 16:52:04.469855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea26f2e4824'
down_revision = '740e06bcdeaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('satuan', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('satuan', 'is_active')
    # ### end Alembic commands ###
