"""alter table role

Revision ID: 349e6b564696
Revises: 1962d3edad1a
Create Date: 2021-12-21 08:54:54.669979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349e6b564696'
down_revision = '1962d3edad1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'is_active')
    # ### end Alembic commands ###
