"""alter table opd dan urusan

Revision ID: 422693177c04
Revises: 2ea26f2e4824
Create Date: 2021-12-20 11:04:47.772491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422693177c04'
down_revision = '2ea26f2e4824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opd', sa.Column('kode', sa.String(length=16), nullable=True))
    op.drop_index('uq_opd_name', table_name='opd')
    op.create_index(op.f('ix_opd_kode'), 'opd', ['kode'], unique=True)
    op.add_column('urusan', sa.Column('kode', sa.String(length=16), nullable=True))
    op.drop_index('uq_urusan_name', table_name='urusan')
    op.create_index(op.f('ix_urusan_kode'), 'urusan', ['kode'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urusan_kode'), table_name='urusan')
    op.create_index('uq_urusan_name', 'urusan', ['name'], unique=False)
    op.drop_column('urusan', 'kode')
    op.drop_index(op.f('ix_opd_kode'), table_name='opd')
    op.create_index('uq_opd_name', 'opd', ['name'], unique=False)
    op.drop_column('opd', 'kode')
    # ### end Alembic commands ###
