"""alter table master_data

Revision ID: 4c48ebfa74bc
Revises: 75c946a8ef00
Create Date: 2021-12-15 14:55:55.275321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c48ebfa74bc'
down_revision = '75c946a8ef00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_data', sa.Column('nasional', sa.Boolean(), nullable=True))
    op.add_column('master_data', sa.Column('provinsi', sa.Boolean(), nullable=True))
    op.add_column('master_data', sa.Column('kabupaten', sa.Boolean(), nullable=True))
    op.add_column('master_data', sa.Column('kecamatan', sa.Boolean(), nullable=True))
    op.add_column('master_data', sa.Column('timeframe', sa.String(length=128), nullable=True))
    op.alter_column('master_data', 'satuan',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(op.f('fk_master_data_satuan_satuan'), 'master_data', 'satuan', ['satuan'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_master_data_satuan_satuan'), 'master_data', type_='foreignkey')
    op.alter_column('master_data', 'satuan',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.drop_column('master_data', 'timeframe')
    op.drop_column('master_data', 'kecamatan')
    op.drop_column('master_data', 'kabupaten')
    op.drop_column('master_data', 'provinsi')
    op.drop_column('master_data', 'nasional')
    # ### end Alembic commands ###
