"""create table input_history

Revision ID: 4f9ed7d0c5f3
Revises: d4775fceedd0
Create Date: 2021-12-08 09:37:12.595598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9ed7d0c5f3'
down_revision = 'd4775fceedd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_data_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_input_history_created_by_user')),
    sa.ForeignKeyConstraint(['input_data_id'], ['input_data.id'], name=op.f('fk_input_history_input_data_id_input_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_input_history'))
    )
    op.create_index(op.f('ix_input_history_created_by'), 'input_history', ['created_by'], unique=False)
    op.create_index(op.f('ix_input_history_id'), 'input_history', ['id'], unique=False)
    op.create_index(op.f('ix_input_history_input_data_id'), 'input_history', ['input_data_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_input_history_input_data_id'), table_name='input_history')
    op.drop_index(op.f('ix_input_history_id'), table_name='input_history')
    op.drop_index(op.f('ix_input_history_created_by'), table_name='input_history')
    op.drop_table('input_history')
    # ### end Alembic commands ###
