"""create table validation_flow

Revision ID: 57a1014f1d48
Revises: a18e08159512
Create Date: 2021-12-30 11:13:17.112657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a1014f1d48'
down_revision = 'a18e08159512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('status_start_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['status_start_id'], ['status.id'], name=op.f('fk_validation_flow_status_start_id_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_flow'))
    )
    op.create_index(op.f('ix_validation_flow_id'), 'validation_flow', ['id'], unique=False)
    op.create_index(op.f('ix_validation_flow_name'), 'validation_flow', ['name'], unique=False)
    op.create_index(op.f('ix_validation_flow_status_start_id'), 'validation_flow', ['status_start_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_flow_status_start_id'), table_name='validation_flow')
    op.drop_index(op.f('ix_validation_flow_name'), table_name='validation_flow')
    op.drop_index(op.f('ix_validation_flow_id'), table_name='validation_flow')
    op.drop_table('validation_flow')
    # ### end Alembic commands ###
