"""alter table satuan_type

Revision ID: 740e06bcdeaa
Revises: d3afb27acfae
Create Date: 2021-12-16 14:21:30.996458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740e06bcdeaa'
down_revision = 'd3afb27acfae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('satuan_type', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('satuan_type', 'is_active')
    # ### end Alembic commands ###
