"""create table satuan

Revision ID: 75c946a8ef00
Revises: 7cfa279fa7ce
Create Date: 2021-12-15 14:40:29.741539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c946a8ef00'
down_revision = '7cfa279fa7ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satuan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type'], ['satuan_type.id'], name=op.f('fk_satuan_type_satuan_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_satuan'))
    )
    op.create_index(op.f('ix_satuan_id'), 'satuan', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_satuan_id'), table_name='satuan')
    op.drop_table('satuan')
    # ### end Alembic commands ###
