"""create table status_update

Revision ID: 7cfa279fa7ce
Revises: ac9628ffd4dd
Create Date: 2021-12-08 13:47:54.659271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cfa279fa7ce'
down_revision = 'ac9628ffd4dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_history_id', sa.Integer(), nullable=True),
    sa.Column('status_updated_to', sa.Integer(), nullable=True),
    sa.Column('status_updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['input_history_id'], ['input_history.id'], name=op.f('fk_status_update_input_history_id_input_history')),
    sa.ForeignKeyConstraint(['status_updated_by'], ['user.id'], name=op.f('fk_status_update_status_updated_by_user')),
    sa.ForeignKeyConstraint(['status_updated_to'], ['status.id'], name=op.f('fk_status_update_status_updated_to_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status_update'))
    )
    op.create_index(op.f('ix_status_update_id'), 'status_update', ['id'], unique=False)
    op.create_index(op.f('ix_status_update_input_history_id'), 'status_update', ['input_history_id'], unique=False)
    op.create_index(op.f('ix_status_update_status_updated_by'), 'status_update', ['status_updated_by'], unique=False)
    op.create_index(op.f('ix_status_update_status_updated_to'), 'status_update', ['status_updated_to'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_update_status_updated_to'), table_name='status_update')
    op.drop_index(op.f('ix_status_update_status_updated_by'), table_name='status_update')
    op.drop_index(op.f('ix_status_update_input_history_id'), table_name='status_update')
    op.drop_index(op.f('ix_status_update_id'), table_name='status_update')
    op.drop_table('status_update')
    # ### end Alembic commands ###
