"""alter table input_data

Revision ID: 81e4be62c368
Revises: 467c99c9a450
Create Date: 2021-12-16 09:53:50.313789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e4be62c368'
down_revision = '467c99c9a450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_data', sa.Column('from_date', sa.Date(), nullable=True))
    op.add_column('input_data', sa.Column('to_date', sa.Date(), nullable=True))
    op.add_column('input_data', sa.Column('notes', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('input_data', 'notes')
    op.drop_column('input_data', 'to_date')
    op.drop_column('input_data', 'from_date')
    # ### end Alembic commands ###
