"""create table urusan

Revision ID: 897e91cdb9ff
Revises: 4f9ed7d0c5f3
Create Date: 2021-12-08 13:10:03.681552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '897e91cdb9ff'
down_revision = '4f9ed7d0c5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urusan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_urusan')),
    sa.UniqueConstraint('name', name=op.f('uq_urusan_name'))
    )
    op.create_index(op.f('ix_urusan_id'), 'urusan', ['id'], unique=False)
    op.add_column('master_data', sa.Column('urusan_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_master_data_opd_id_opd', 'master_data', type_='foreignkey')
    op.create_foreign_key(op.f('fk_master_data_urusan_id_urusan'), 'master_data', 'urusan', ['urusan_id'], ['id'])
    op.drop_column('master_data', 'opd_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_data', sa.Column('opd_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_master_data_urusan_id_urusan'), 'master_data', type_='foreignkey')
    op.create_foreign_key('fk_master_data_opd_id_opd', 'master_data', 'opd', ['opd_id'], ['id'])
    op.drop_column('master_data', 'urusan_id')
    op.drop_index(op.f('ix_urusan_id'), table_name='urusan')
    op.drop_table('urusan')
    # ### end Alembic commands ###
