"""alter table status

Revision ID: a18e08159512
Revises: 11057ca26636
Create Date: 2021-12-30 10:46:14.184132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18e08159512'
down_revision = '11057ca26636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'is_active')
    # ### end Alembic commands ###
