"""create table opd_urusan

Revision ID: ac9628ffd4dd
Revises: 897e91cdb9ff
Create Date: 2021-12-08 13:23:15.510120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9628ffd4dd'
down_revision = '897e91cdb9ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opd_urusan',
    sa.Column('opd_id', sa.Integer(), nullable=False),
    sa.Column('urusan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opd_id'], ['opd.id'], name=op.f('fk_opd_urusan_opd_id_opd')),
    sa.ForeignKeyConstraint(['urusan_id'], ['urusan.id'], name=op.f('fk_opd_urusan_urusan_id_urusan')),
    sa.PrimaryKeyConstraint('opd_id', 'urusan_id', name=op.f('pk_opd_urusan'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opd_urusan')
    # ### end Alembic commands ###
