"""alter table user

Revision ID: d3afb27acfae
Revises: 81e4be62c368
Create Date: 2021-12-16 10:13:14.943676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3afb27acfae'
down_revision = '81e4be62c368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nip', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('no_hp', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('no_kantor', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('jabatan', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'jabatan')
    op.drop_column('user', 'no_kantor')
    op.drop_column('user', 'no_hp')
    op.drop_column('user', 'nip')
    # ### end Alembic commands ###
