"""create table input_data

Revision ID: d4775fceedd0
Revises: 0398ad4f485f
Create Date: 2021-12-07 16:40:28.342041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4775fceedd0'
down_revision = '0398ad4f485f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_input_data_created_by_user')),
    sa.ForeignKeyConstraint(['master_id'], ['master_data.id'], name=op.f('fk_input_data_master_id_master_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_input_data'))
    )
    op.create_index(op.f('ix_input_data_created_by'), 'input_data', ['created_by'], unique=False)
    op.create_index(op.f('ix_input_data_id'), 'input_data', ['id'], unique=False)
    op.create_index(op.f('ix_input_data_master_id'), 'input_data', ['master_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_input_data_master_id'), table_name='input_data')
    op.drop_index(op.f('ix_input_data_id'), table_name='input_data')
    op.drop_index(op.f('ix_input_data_created_by'), table_name='input_data')
    op.drop_table('input_data')
    # ### end Alembic commands ###
