"""create table status

Revision ID: edd2abd9d638
Revises: 3313885c7c9e
Create Date: 2021-12-07 15:25:45.929062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd2abd9d638'
down_revision = '3313885c7c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['status.id'], name=op.f('fk_status_parent_id_status')),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_status_role_id_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status')),
    sa.UniqueConstraint('name', name=op.f('uq_status_name'))
    )
    op.create_index(op.f('ix_status_id'), 'status', ['id'], unique=False)
    op.create_index(op.f('ix_status_parent_id'), 'status', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_parent_id'), table_name='status')
    op.drop_index(op.f('ix_status_id'), table_name='status')
    op.drop_table('status')
    # ### end Alembic commands ###
