"""create table OPD

Revision ID: fabaead42a5b
Revises: 7f3da12fe796
Create Date: 2021-12-07 15:05:32.100802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fabaead42a5b'
down_revision = '7f3da12fe796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opd')),
    sa.UniqueConstraint('name', name=op.f('uq_opd_name'))
    )
    op.create_index(op.f('ix_opd_id'), 'opd', ['id'], unique=False)
    op.add_column('user', sa.Column('opd_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_user_opd_id_opd'), 'user', 'opd', ['opd_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_opd_id_opd'), 'user', type_='foreignkey')
    op.drop_column('user', 'opd_id')
    op.drop_index(op.f('ix_opd_id'), table_name='opd')
    op.drop_table('opd')
    # ### end Alembic commands ###
